project:
  type: website
  render:
    - "**.qmd"
    - "!templates/*.qmd"
  output-dir: docs

website:
  title: The Healthcare Service Analytics & Decision Intelligence Atlas
  draft-mode: unlinked
  site-url: https://atlas.hsma.co.uk
  description: "A guide to modern healthcare analytics, modelling and data science"
  google-analytics:
    tracking-id: "G-41QML5TFEF"
    anonymize-ip: true
  cookie-consent:
    type: express
    style: simple
    palette: dark
  navbar:
    title: false
    collapse-below: "xl"
    tools:
      - icon: github
        menu:
          - text: View the code for this website
            href:  https://github.com/bergam0t/decision_intelligence_atlas
    right:
      - href: index.qmd
        text: Welcome

      - href: packages_projects_tools/packages_projects_tools.qmd
        text: Packages, Projects and Tools

      - href: techniques/techniques.qmd
        text: Techniques

      - href: graph_catalogue/graph_catalogue.qmd
        text: Graph Catalogue

      - href: about.qmd
        text: About

language:
  title-block-published: "Page last modified"

format:
  html:
    theme:
      light:
      - flatly
      - resources/themes/theme-light.scss
      - resources/fonts/css/lexend.css
      dark:
      - darkly
      - resources/themes/theme-dark.scss
      - resources/fonts/css/lexend.css
    css: resources/themes/styles.css
    toc: true
    mainfont: Lexend
    include-in-header:
      file: resources/header.html
    include-before-body: 
      file: resources/post-header.html
    title-block-banner: true
