project:
  type: website
  render:
    - "**.qmd"
    - "!templates/*.qmd"
  output-dir: docs

website:
  title: The Healthcare Service Analytics & Decision Intelligence Atlas
  draft-mode: unlinked
  site-url: https://atlas.hsma.co.uk
  description: "A guide to modern healthcare analytics, modelling and data science"
  navbar:
    title: false
    collapse-below: "xl"
    tools:
      - icon: github
        menu:
          - text: View the code for this website
            href:  https://github.com/bergam0t/decision_intelligence_atlas
    right:
      - href: index.qmd
        text: Welcome

      - href: packages_projects_tools/packages_projects_tools.qmd
        text: Packages, Projects and Tools

      - href: techniques/techniques.qmd
        text: Techniques

      - href: graph_catalogue/graph_catalogue.qmd
        text: Graph Catalogue

      - href: about_hsma.qmd
        text: About HSMA

format:
  html:
    theme:
      dark:
      - darkly
      - resources/themes/theme-dark.scss
      - resources/fonts/css/lexend.css
      light:
      - flatly
      - resources/themes/theme-light.scss
      - resources/fonts/css/lexend.css
    css: resources/themes/styles.css
    toc: true
    title-block-banner: resources/banner.png
    mainfont: Lexend
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
