# .github/workflows/quarto-check.yml
on:
  pull_request:

name: Quarto Check for Tools, Packages and Techniques Submission from Form

on:
  workflow_run:
    workflows: ["Commit and open PR"]  # name of your PR-creating workflow
    types:
      - completed

jobs:
  check:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Render (test build)
        run: quarto render
